// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3727556e-5d56-459b-ad8e-5aa61cc425d3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_e9xaRasMn",
    "aws_user_pools_web_client_id": "4ovuuvt9mj1tia35pqugah17fj",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "studentsapi",
            "endpoint": "https://p714kevuqi.execute-api.us-east-1.amazonaws.com/projectenv",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "answersTable-projectenv",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
