// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cf93ffd5-a5fe-4065-87e0-25bda4db7260",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XgMdrTwkW",
    "aws_user_pools_web_client_id": "6nbs7qktlu1s6nc9ec81u55dg9",
    "oauth": {}
};


export default awsmobile;
