// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4ea0d418-9b39-46c5-be88-8dee4ecd5ba5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZtRDdfnti",
    "aws_user_pools_web_client_id": "4j7da43vumjdamb7cs5b0lbjck",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "students",
            "endpoint": "https://v509tp25ad.execute-api.us-east-1.amazonaws.com/loginenv",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "studentResponses-loginenv",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
